// flow-typed signature: 611eeb4ee0bd113f0fafe4351d76dd12
// flow-typed version: <<STUB>>/react-query/devtools_v*/flow_v0.151.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-query/devtools'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-query/devtools' {
    declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'react-query/devtools/index' {
    declare module.exports: $Exports<'react-query/devtools'>
}
declare module 'react-query/devtools/index.js' {
    declare module.exports: $Exports<'react-query/devtools'>
}
